version: '3'

tasks:
  up:
    deps:
      - caddyup
      - appstart
      - webstart

  installdeps:
    cmds:
      - brew install caddy rtx
      - rtx install
    preconditions:
      - which brew

  caddyup:
    cmds:
      - caddy run
    preconditions:
      - which caddy

  caddysetup:
    cmds:
      - caddy trust
    preconditions:
      - which caddy

  testall:
    aliases: [test]
    deps:
      - apptest
      - webtest

  appstart:
    dir: app_ash
    cmds:
      - mix phx.server

  apptest:
    dir: app_ash
    cmds:
      - mix test

  webstart:
    dir: web
    cmds:
      - npm run dev

  webtest:
    dir: web
    cmds:
      - npm run test

  webwatch:
    dir: web
    cmds:
      - npm run test:unit

  webcov:
    dir: web
    cmds:
      - npm run test:cov
