version: '3'

tasks:
  up:
    deps:
      - caddyup
      - appstart
      - frontstart

  installdeps:
    deps:
      - installcaddy
      - installrtx
      - installlanguages

  caddyup:
    deps: [setup]
    cmds:
      - caddy run

  testall:
    aliases: [test]
    deps:
      - apptest
      - fronttest

  appstart:
    dir: back
    cmds:
      - mix phx.server

  apptest:
    dir: back
    cmds:
      - mix test

  frontstart:
    dir: front
    cmds:
      - npm run dev

  fronttest:
    dir: front
    cmds:
      - npm run test

  frontwatch:
    dir: front
    cmds:
      - npm run test:unit

  frontcov:
    dir: front
    cmds:
      - npm run test:cov
