version: '3'

tasks:
  up:
    deps:
      - caddyup
      - appstart
      - webstart

  installdeps:
    deps:
      - installcaddy
      - installrtx
      - installlanguages

  caddyup:
    # deps: [setup] TODO
    cmds:
      - caddy run

  testall:
    aliases: [test]
    deps:
      - apptest
      - webtest

  appstart:
    dir: app
    cmds:
      - mix phx.server

  apptest:
    dir: app
    cmds:
      - mix test

  webstart:
    dir: web
    cmds:
      - npm run dev

  webtest:
    dir: web
    cmds:
      - npm run test

  webwatch:
    dir: web
    cmds:
      - npm run test:unit

  webcov:
    dir: web
    cmds:
      - npm run test:cov
