/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/circles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description /circles operation on circle resource */
		get: {
			parameters: {
				query?: {
					/** @description Filters the query to results with attributes matching the given filter object */
					filter?: components["schemas"]["circle-filter"];
					/** @description Sort order to apply to the results */
					sort?: string;
					/** @description Paginates the response with the limit and offset or keyset pagination. */
					page?: {
						after?: string;
						before?: string;
						/** @default false */
						count?: boolean;
						limit?: number;
						offset?: number;
					};
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for circle
						 * @example id,name,system_type,description
						 */
						circle?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							/** @description An array of resource objects representing a circle */
							data?: components["schemas"]["circle"][];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		/** @description Create a custom circle */
		post: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for circle
						 * @example id,name,system_type,description
						 */
						circle?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Request body for the /circles operation on circle resource */
			requestBody: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: {
								description?: string | null;
								name: string;
							};
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "circle";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["circle"];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/circles/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description /circles/:id operation on circle resource */
		get: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for circle
						 * @example id,name,system_type,description
						 */
						circle?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["circle"];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		/** @description Delete a custom circle */
		delete: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for circle
						 * @example id,name,system_type,description
						 */
						circle?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deleted successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				default: components["responses"]["errors"];
			};
		};
		options?: never;
		head?: never;
		/** @description Update a custom circle (name, description) */
		patch: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for circle
						 * @example id,name,system_type,description
						 */
						circle?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			/** @description Request body for the /circles/:id operation on circle resource */
			requestBody?: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: {
								description?: string | null;
								name?: string | null;
							};
							id: string;
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "circle";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["circle"];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		trace?: never;
	};
	"/api/connections": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description List the current user's accepted connections */
		get: {
			parameters: {
				query?: {
					/** @description Filters the query to results with attributes matching the given filter object */
					filter?: components["schemas"]["connection-filter"];
					/** @description Sort order to apply to the results */
					sort?: string;
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							/** @description An array of resource objects representing a connection */
							data?: components["schemas"]["connection"][];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		/** @description Send a connection request to another user */
		post: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Request body for the /connections operation on connection resource */
			requestBody: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: {
								/**
								 * Format: uuid
								 * @description The user to send the request to
								 */
								receiver_id: string;
							};
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "connection";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["connection"];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connections/pending-incoming": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description List pending connection requests received by the current user */
		get: {
			parameters: {
				query?: {
					/** @description Filters the query to results with attributes matching the given filter object */
					filter?: components["schemas"]["connection-filter"];
					/** @description Sort order to apply to the results */
					sort?: string;
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							/** @description An array of resource objects representing a connection */
							data?: components["schemas"]["connection"][];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connections/pending-outgoing": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description List pending connection requests sent by the current user */
		get: {
			parameters: {
				query?: {
					/** @description Filters the query to results with attributes matching the given filter object */
					filter?: components["schemas"]["connection-filter"];
					/** @description Sort order to apply to the results */
					sort?: string;
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							/** @description An array of resource objects representing a connection */
							data?: components["schemas"]["connection"][];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connections/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description /connections/:id operation on connection resource */
		get: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["connection"];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		/** @description Remove an existing connection (either party can do this) */
		delete: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deleted successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				default: components["responses"]["errors"];
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connections/{id}/accept": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** @description Accept a pending connection request */
		patch: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			/** @description Request body for the /connections/:id/accept operation on connection resource */
			requestBody?: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: Record<string, never>;
							id: string;
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "connection";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["connection"];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		trace?: never;
	};
	"/api/connections/{id}/reject": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** @description Reject a pending connection request */
		patch: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for connection
						 * @example id,requester_id,receiver_id
						 */
						connection?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			/** @description Request body for the /connections/:id/reject operation on connection resource */
			requestBody?: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: Record<string, never>;
							id: string;
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "connection";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["connection"];
							included?: components["schemas"]["user"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		trace?: never;
	};
	"/api/profiles/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description /profiles/:id operation on profile resource */
		get: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for profile
						 * @example id,display_name,handle,bio,avatar_url,location,profile_visibility,comment_visibility,user_id
						 */
						profile?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["profile"];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** @description Update profile fields (supports partial updates for inline editing) */
		patch: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for profile
						 * @example id,display_name,handle,bio,avatar_url,location,profile_visibility,comment_visibility,user_id
						 */
						profile?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			/** @description Request body for the /profiles/:id operation on profile resource */
			requestBody?: {
				content: {
					"application/vnd.api+json": {
						data: {
							attributes?: {
								avatar_url?: string | null;
								bio?: string | null;
								comment_visibility?:
									| ("connections_and_group_members" | "everyone_on_post")
									| null;
								display_name?: string | null;
								handle?: string | null;
								location?: string | null;
								profile_visibility?: ("connections_only" | "public") | null;
							};
							id: string;
							relationships?: Record<string, never>;
							/** @enum {unknown} */
							type?: "profile";
						};
					};
				};
			};
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["profile"];
							included?: unknown[];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		trace?: never;
	};
	"/api/users/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Search for users by handle or display name */
		get: {
			parameters: {
				query: {
					/** @description Filters the query to results with attributes matching the given filter object */
					filter?: components["schemas"]["user-filter"];
					/** @description Sort order to apply to the results */
					sort?: string;
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for user
						 * @example id,email
						 */
						user?: string;
					} & {
						[key: string]: unknown;
					};
					query: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							/** @description An array of resource objects representing a user */
							data?: components["schemas"]["user"][];
							included?: components["schemas"]["profile"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description /users/:id operation on user resource */
		get: {
			parameters: {
				query?: {
					/** @description Relationship paths to include in the response */
					include?: string;
					/** @description Limits the response fields to only those listed for each type */
					fields?: {
						/**
						 * @description Comma separated field names for user
						 * @example id,email
						 */
						user?: string;
					} & {
						[key: string]: unknown;
					};
				};
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/vnd.api+json": {
							data?: components["schemas"]["user"];
							included?: components["schemas"]["profile"][];
							meta?: {
								[key: string]: unknown;
							};
						};
					};
				};
				default: components["responses"]["errors"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description A "Resource object" representing a circle */
		circle: {
			/** @description An attributes object for a circle */
			attributes?: {
				/** @description Field included by default. */
				description?: (string | null) | null;
				/** @description Field included by default. */
				name: string;
				/** @description Deprecated: system circles are now virtual. Kept for backwards compatibility. Field included by default. */
				system_type?: ("private" | "all_friends" | "public" | null) | null;
			};
			id: string;
			/** @description A relationships object for a circle */
			relationships?: Record<string, never>;
			type: string;
		};
		/**
		 * @description Filters the query to results matching the given filter object
		 * @example
		 */
		"circle-filter": {
			and?: components["schemas"]["circle-filter"][];
			description?: components["schemas"]["circle-filter-description"];
			id?: components["schemas"]["circle-filter-id"];
			name?: components["schemas"]["circle-filter-name"];
			not?: components["schemas"]["circle-filter"];
			or?: components["schemas"]["circle-filter"][];
			system_type?: components["schemas"]["circle-filter-system_type"];
		};
		"circle-filter-description": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"circle-filter-id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		"circle-filter-name": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		/** @description Deprecated: system circles are now virtual. Kept for backwards compatibility. */
		"circle-filter-system_type": {
			/** @enum {string} */
			eq?: "private" | "all_friends" | "public";
			/** @enum {string} */
			greater_than?: "private" | "all_friends" | "public";
			/** @enum {string} */
			greater_than_or_equal?: "private" | "all_friends" | "public";
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** @enum {string} */
			less_than?: "private" | "all_friends" | "public";
			/** @enum {string} */
			less_than_or_equal?: "private" | "all_friends" | "public";
			/** @enum {string} */
			not_eq?: "private" | "all_friends" | "public";
		};
		/** @description A "Resource object" representing a connection */
		connection: {
			/** @description An attributes object for a connection */
			attributes?: {
				/**
				 * Format: uuid
				 * @description Field included by default.
				 */
				receiver_id: string;
				/**
				 * Format: uuid
				 * @description Field included by default.
				 */
				requester_id: string;
			};
			id: string;
			/** @description A relationships object for a connection */
			relationships?: {
				receiver?: {
					/** @description An identifier for receiver */
					data?: {
						id: string;
						meta?: {
							[key: string]: unknown;
						};
						type: string;
					} | null;
				};
				requester?: {
					/** @description An identifier for requester */
					data?: {
						id: string;
						meta?: {
							[key: string]: unknown;
						};
						type: string;
					} | null;
				};
			};
			type: string;
		};
		/**
		 * @description Filters the query to results matching the given filter object
		 * @example
		 */
		"connection-filter": {
			and?: components["schemas"]["connection-filter"][];
			id?: components["schemas"]["connection-filter-id"];
			not?: components["schemas"]["connection-filter"];
			or?: components["schemas"]["connection-filter"][];
			receiver?: components["schemas"]["user-filter"];
			receiver_id?: components["schemas"]["connection-filter-receiver_id"];
			requester?: components["schemas"]["user-filter"];
			requester_id?: components["schemas"]["connection-filter-requester_id"];
		};
		"connection-filter-id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		"connection-filter-receiver_id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		"connection-filter-requester_id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		error: {
			/** @description An application-specific error code, expressed as a string value. */
			code?: string;
			/** @description A human-readable explanation specific to this occurrence of the problem. */
			detail?: string;
			/** @description A unique identifier for this particular occurrence of the problem. */
			id?: string;
			links?: components["schemas"]["links"];
			source?: {
				/** @description A string indicating which query parameter caused the error. */
				parameter?: string;
				/** @description A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute]. */
				pointer?: string;
			};
			/** @description The HTTP status code applicable to this problem, expressed as a string value. */
			status?: string;
			/** @description A short, human-readable summary of the problem. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization. */
			title?: string;
		};
		errors: components["schemas"]["error"][];
		/** @description A link MUST be represented as either: a string containing the link's URL or a link object. */
		link: string;
		links: {
			[key: string]: components["schemas"]["link"];
		};
		/** @description A "Resource object" representing a profile */
		profile: {
			/** @description An attributes object for a profile */
			attributes?: {
				/** @description Field included by default. */
				avatar_url?: (string | null) | null;
				/** @description Field included by default. */
				bio?: (string | null) | null;
				/**
				 * @description Field included by default.
				 * @enum {string}
				 */
				comment_visibility:
					| "connections_and_group_members"
					| "everyone_on_post";
				/** @description Field included by default. */
				display_name?: (string | null) | null;
				/** @description Field included by default. */
				handle?: (string | null) | null;
				/** @description Field included by default. */
				location?: (string | null) | null;
				/**
				 * @description Field included by default.
				 * @enum {string}
				 */
				profile_visibility: "connections_only" | "public";
				/**
				 * Format: uuid
				 * @description Field included by default.
				 */
				user_id: string;
			};
			id: string;
			/** @description A relationships object for a profile */
			relationships?: {
				user?: {
					/** @description An identifier for user */
					data?: {
						id: string;
						meta?: {
							[key: string]: unknown;
						};
						type: string;
					} | null;
				};
			};
			type: string;
		};
		/**
		 * @description Filters the query to results matching the given filter object
		 * @example
		 */
		"profile-filter": {
			and?: components["schemas"]["profile-filter"][];
			avatar_url?: components["schemas"]["profile-filter-avatar_url"];
			bio?: components["schemas"]["profile-filter-bio"];
			comment_visibility?: components["schemas"]["profile-filter-comment_visibility"];
			display_name?: components["schemas"]["profile-filter-display_name"];
			handle?: components["schemas"]["profile-filter-handle"];
			id?: components["schemas"]["profile-filter-id"];
			location?: components["schemas"]["profile-filter-location"];
			not?: components["schemas"]["profile-filter"];
			or?: components["schemas"]["profile-filter"][];
			profile_visibility?: components["schemas"]["profile-filter-profile_visibility"];
			user?: components["schemas"]["user-filter"];
			user_id?: components["schemas"]["profile-filter-user_id"];
		};
		"profile-filter-avatar_url": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"profile-filter-bio": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"profile-filter-comment_visibility": {
			/** @enum {string} */
			eq?: "connections_and_group_members" | "everyone_on_post";
			/** @enum {string} */
			greater_than?: "connections_and_group_members" | "everyone_on_post";
			/** @enum {string} */
			greater_than_or_equal?:
				| "connections_and_group_members"
				| "everyone_on_post";
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** @enum {string} */
			less_than?: "connections_and_group_members" | "everyone_on_post";
			/** @enum {string} */
			less_than_or_equal?: "connections_and_group_members" | "everyone_on_post";
			/** @enum {string} */
			not_eq?: "connections_and_group_members" | "everyone_on_post";
		};
		"profile-filter-display_name": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"profile-filter-handle": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"profile-filter-id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		"profile-filter-location": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			ilike?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			like?: string;
			not_eq?: string;
		};
		"profile-filter-profile_visibility": {
			/** @enum {string} */
			eq?: "connections_only" | "public";
			/** @enum {string} */
			greater_than?: "connections_only" | "public";
			/** @enum {string} */
			greater_than_or_equal?: "connections_only" | "public";
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** @enum {string} */
			less_than?: "connections_only" | "public";
			/** @enum {string} */
			less_than_or_equal?: "connections_only" | "public";
			/** @enum {string} */
			not_eq?: "connections_only" | "public";
		};
		"profile-filter-user_id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
		/** @description A "Resource object" representing a user */
		user: {
			/** @description An attributes object for a user */
			attributes?: {
				/** @description Field included by default. */
				email: string;
				/** @description Virtual system circles defined in code, not the database */
				system_circles?: (unknown[] | null) | null;
			};
			id: string;
			/** @description A relationships object for a user */
			relationships?: {
				profile?: {
					/** @description An identifier for profile */
					data?: {
						id: string;
						meta?: {
							[key: string]: unknown;
						};
						type: string;
					} | null;
				};
			};
			type: string;
		};
		/**
		 * @description Filters the query to results matching the given filter object
		 * @example
		 */
		"user-filter": {
			and?: components["schemas"]["user-filter"][];
			email?: components["schemas"]["user-filter-email"];
			id?: components["schemas"]["user-filter-id"];
			not?: components["schemas"]["user-filter"];
			or?: components["schemas"]["user-filter"][];
			profile?: components["schemas"]["profile-filter"];
		};
		"user-filter-email": {
			contains?: string;
			eq?: string;
			greater_than?: string;
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			less_than?: string;
			less_than_or_equal?: string;
			not_eq?: string;
		};
		"user-filter-id": {
			/** Format: uuid */
			eq?: string;
			/** Format: uuid */
			greater_than?: string;
			/** Format: uuid */
			greater_than_or_equal?: string;
			in?: string[];
			is_distinct_from?: string;
			is_nil?: boolean;
			is_not_distinct_from?: string;
			/** Format: uuid */
			less_than?: string;
			/** Format: uuid */
			less_than_or_equal?: string;
			/** Format: uuid */
			not_eq?: string;
		};
	};
	responses: {
		/** @description General Error */
		errors: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/vnd.api+json": components["schemas"]["errors"];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
