defmodule Bubbli.Repo.Migrations.CreateCircles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:circles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :type, :text, null: false
      add :system_type, :text
      add :description, :text

      add :owner_id,
          references(:users,
            column: :id,
            name: "circles_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:circles, [:owner_id, :system_type],
             name: "circles_unique_system_circle_index",
             where: "(type = 'system')"
           )

    create table(:circle_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :circle_id,
          references(:circles,
            column: :id,
            name: "circle_members_circle_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "circle_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:circle_members, [:circle_id, :user_id],
             name: "circle_members_unique_circle_member_index"
           )
  end

  def down do
    drop_if_exists unique_index(:circle_members, [:circle_id, :user_id],
                     name: "circle_members_unique_circle_member_index"
                   )

    drop constraint(:circle_members, "circle_members_circle_id_fkey")

    drop constraint(:circle_members, "circle_members_user_id_fkey")

    drop table(:circle_members)

    drop_if_exists unique_index(:circles, [:owner_id, :system_type],
                     name: "circles_unique_system_circle_index"
                   )

    drop constraint(:circles, "circles_owner_id_fkey")

    drop table(:circles)
  end
end
