defmodule Bubbli.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :display_name, :text
      add :handle, :text
      add :bio, :text
      add :avatar_url, :text
      add :profile_visibility, :text, null: false, default: "connections_only"
      add :comment_visibility, :text, null: false, default: "connections_and_group_members"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:handle], name: "users_unique_handle_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :comment_visibility
      remove :profile_visibility
      remove :avatar_url
      remove :bio
      remove :handle
      remove :display_name
    end
  end
end
