defmodule Bubbli.Repo.Migrations.CleanupCircles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:circles) do
      remove :system_type
      remove :type
    end
  end

  def down do
    alter table(:circles) do
      add :type, :text, null: false, default: "custom"
      add :system_type, :text
    end
  end
end
