defmodule Bubbli.Repo.Migrations.AddGroupsAndPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:post_audiences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "post_audiences_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :circle_id,
          references(:circles,
            column: :id,
            name: "post_audiences_circle_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :group_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:post_audiences) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "post_audiences_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:groups) do
      add :name, :text, null: false
      add :description, :text
      add :cover_image_url, :text
      add :privacy, :text, null: false, default: "public"

      add :owner_id,
          references(:users,
            column: :id,
            name: "groups_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:group_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_members_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "group_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:group_members, [:group_id, :user_id],
             name: "group_members_unique_group_member_index"
           )
  end

  def down do
    drop constraint(:group_members, "group_members_group_id_fkey")

    drop constraint(:group_members, "group_members_user_id_fkey")

    drop_if_exists unique_index(:group_members, [:group_id, :user_id],
                     name: "group_members_unique_group_member_index"
                   )

    drop table(:group_members)

    drop constraint(:groups, "groups_owner_id_fkey")

    alter table(:groups) do
      remove :updated_at
      remove :inserted_at
      remove :owner_id
      remove :privacy
      remove :cover_image_url
      remove :description
      remove :name
    end

    drop constraint(:post_audiences, "post_audiences_group_id_fkey")

    alter table(:post_audiences) do
      modify :group_id, :uuid
    end

    drop table(:groups)

    drop constraint(:post_audiences, "post_audiences_post_id_fkey")

    drop constraint(:post_audiences, "post_audiences_circle_id_fkey")

    drop table(:post_audiences)

    drop constraint(:posts, "posts_author_id_fkey")

    drop table(:posts)
  end
end
