defmodule Bubbli.Repo.Migrations.AddScoredFeed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :last_feed_viewed_at, :utc_datetime_usec
    end

    create index(:post_audiences, [:post_id, :type])
  end

  def down do
    drop_if_exists index(:post_audiences, [:post_id, :type])

    alter table(:users) do
      remove :last_feed_viewed_at
    end
  end
end
