defmodule Bubbli.Repo.Migrations.Initialize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:last_feed_viewed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:users, [:email], name: "users_unique_email_index"))

    create table(:tokens, primary_key: false) do
      add(:jti, :text, null: false, primary_key: true)
      add(:subject, :text, null: false)
      add(:expires_at, :utc_datetime, null: false)
      add(:purpose, :text, null: false)
      add(:extra_data, :map)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:profiles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:display_name, :text)
      add(:handle, :text)
      add(:bio, :text)
      add(:avatar_url, :text)
      add(:location, :text)
      add(:profile_visibility, :text, null: false, default: "connections_only")
      add(:comment_visibility, :text, null: false, default: "connections_and_group_members")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "profiles_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(unique_index(:profiles, [:handle], name: "profiles_unique_handle_index"))

    create(unique_index(:profiles, [:user_id], name: "profiles_unique_user_index"))

    create table(:posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:body, :text, null: false)

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "posts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:post_audiences, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "post_audiences_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:circle_id, :uuid)
      add(:group_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:post_audiences, [:post_id, :type]))

    create table(:groups, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:cover_image_url, :text)
      add(:privacy, :text, null: false, default: "public")

      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "groups_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:group_members, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :group_id,
        references(:groups,
          column: :id,
          name: "group_members_group_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "group_members_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:role, :text, null: false, default: "member")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:group_members, [:group_id, :user_id],
        name: "group_members_unique_group_member_index"
      )
    )

    create table(:connections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "connections_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :peer_id,
        references(:users,
          column: :id,
          name: "connections_peer_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:connections, [:user_id, :peer_id], name: "connections_unique_edge_index")
    )

    create table(:connection_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :requester_id,
        references(:users,
          column: :id,
          name: "connection_requests_requester_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :receiver_id,
        references(:users,
          column: :id,
          name: "connection_requests_receiver_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      index(:connection_requests, [:requester_id, :receiver_id],
        name: "connection_requests_unique_pending_index",
        unique: true,
        where: "status = 'pending'"
      )
    )

    create table(:circles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:post_audiences) do
      modify(
        :circle_id,
        references(:circles,
          column: :id,
          name: "post_audiences_circle_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :group_id,
        references(:groups,
          column: :id,
          name: "post_audiences_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:circles) do
      add(:name, :text, null: false)
      add(:description, :text)

      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "circles_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:circle_members, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :circle_id,
        references(:circles,
          column: :id,
          name: "circle_members_circle_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "circle_members_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:circle_members, [:circle_id, :user_id],
        name: "circle_members_unique_circle_member_index"
      )
    )
  end

  def down do
    drop(constraint(:circle_members, "circle_members_circle_id_fkey"))

    drop(constraint(:circle_members, "circle_members_user_id_fkey"))

    drop_if_exists(
      unique_index(:circle_members, [:circle_id, :user_id],
        name: "circle_members_unique_circle_member_index"
      )
    )

    drop(table(:circle_members))

    drop(constraint(:circles, "circles_owner_id_fkey"))

    alter table(:circles) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:owner_id)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:post_audiences, "post_audiences_circle_id_fkey"))

    drop(constraint(:post_audiences, "post_audiences_group_id_fkey"))

    alter table(:post_audiences) do
      modify(:group_id, :uuid)
      modify(:circle_id, :uuid)
    end

    drop(table(:circles))

    drop(constraint(:connection_requests, "connection_requests_requester_id_fkey"))

    drop(constraint(:connection_requests, "connection_requests_receiver_id_fkey"))

    drop_if_exists(
      index(:connection_requests, [:requester_id, :receiver_id],
        name: "connection_requests_unique_pending_index"
      )
    )

    drop(table(:connection_requests))

    drop(constraint(:connections, "connections_user_id_fkey"))

    drop(constraint(:connections, "connections_peer_id_fkey"))

    drop_if_exists(
      unique_index(:connections, [:user_id, :peer_id], name: "connections_unique_edge_index")
    )

    drop(table(:connections))

    drop(constraint(:group_members, "group_members_group_id_fkey"))

    drop(constraint(:group_members, "group_members_user_id_fkey"))

    drop_if_exists(
      unique_index(:group_members, [:group_id, :user_id],
        name: "group_members_unique_group_member_index"
      )
    )

    drop(table(:group_members))

    drop(constraint(:groups, "groups_owner_id_fkey"))

    drop(table(:groups))

    drop(constraint(:post_audiences, "post_audiences_post_id_fkey"))

    drop_if_exists(index(:post_audiences, [:post_id, :type]))

    drop(table(:post_audiences))

    drop(constraint(:posts, "posts_author_id_fkey"))

    drop(table(:posts))

    drop(constraint(:profiles, "profiles_user_id_fkey"))

    drop_if_exists(unique_index(:profiles, [:user_id], name: "profiles_unique_user_index"))

    drop_if_exists(unique_index(:profiles, [:handle], name: "profiles_unique_handle_index"))

    drop(table(:profiles))

    drop(table(:tokens))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop(table(:users))
  end
end
