defmodule Bubbli.Repo.Migrations.SeparateProfileFromUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :comment_visibility
      remove :profile_visibility
      remove :avatar_url
      remove :bio
      remove :handle
      remove :display_name
    end

    drop_if_exists unique_index(:users, [:handle], name: "users_unique_handle_index")

    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :display_name, :text
      add :handle, :text
      add :bio, :text
      add :avatar_url, :text
      add :location, :text
      add :profile_visibility, :text, null: false, default: "connections_only"
      add :comment_visibility, :text, null: false, default: "connections_and_group_members"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:profiles, [:handle], name: "profiles_unique_handle_index")

    create unique_index(:profiles, [:user_id], name: "profiles_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:profiles, [:user_id], name: "profiles_unique_user_index")

    drop_if_exists unique_index(:profiles, [:handle], name: "profiles_unique_handle_index")

    drop constraint(:profiles, "profiles_user_id_fkey")

    drop table(:profiles)

    create unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:users) do
      add :display_name, :text
      add :handle, :text
      add :bio, :text
      add :avatar_url, :text
      add :profile_visibility, :text, null: false, default: "connections_only"
      add :comment_visibility, :text, null: false, default: "connections_and_group_members"
    end
  end
end
