defmodule Bubbli.Repo.Migrations.CreateConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :requester_id,
          references(:users,
            column: :id,
            name: "connections_requester_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :receiver_id,
          references(:users,
            column: :id,
            name: "connections_receiver_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:connections, [:requester_id, :receiver_id],
             name: "connections_unique_connection_pair_index"
           )

    alter table(:circles) do
      modify :type, :text, default: "custom"
    end

    drop_if_exists unique_index(:circles, [:owner_id, :system_type],
                     name: "circles_unique_system_circle_index"
                   )
  end

  def down do
    create unique_index(:circles, [:owner_id, :system_type],
             name: "circles_unique_system_circle_index",
             where: "(type = 'system')"
           )

    alter table(:circles) do
      modify :type, :text, default: nil
    end

    drop_if_exists unique_index(:connections, [:requester_id, :receiver_id],
                     name: "connections_unique_connection_pair_index"
                   )

    drop constraint(:connections, "connections_requester_id_fkey")

    drop constraint(:connections, "connections_receiver_id_fkey")

    drop table(:connections)
  end
end
